services:

  jekyll:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - RUBY_VERSION=${RUBY_VERSION}
    command: bundle exec jekyll serve --host 0.0.0.0
    ports:
      - "4000:4000"
    volumes:
      - ./portfolio:/jekyll
      - root_data:/root
      - gem_data:/usr/local/bundle

volumes:
  root_data:
  gem_data:
